version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - C:/Users/simon/Downloads/airflow-aws/credential.txt:/usr/local/airflow/dags/credential.txt

volumes:
  postgres_data: